import Head from 'next/head'
import styles from '../styles/Home.module.css'
import About from './About'
import ProductContainer from './ProductContainer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://app.snipcart.com" />
        <link rel="preconnect" href="https://cdn.snipcart.com" />
        <link rel="stylesheet" href="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.css" />
      </Head>

      <main className={styles.main}>
        <div>
          <About />
          <ProductContainer />
        </div>

        
      </main>

      <footer className={styles.footer}>
        <script async src="https://cdn.snipcart.com/themes/v3.2.2/default/snipcart.js" />
        <div hidden id="snipcart" data-api-key="NGE2ZDU0MGMtMjQwNS00MjU3LWFiOGUtMDJjY2FlMzZmYzE5NjM3NzYwMDY0OTQ0NzUwNDY4" />
      </footer>
    </div>
  )
}
